#!/usr/bin/env python3

import platform, sys

MINIMUM_VERSION = (3, 4, 0)

if sys.version_info < MINIMUM_VERSION:
    raise EnvironmentError(
        'BiblioPixel needs Python %s or later: your Python version is %s' % (
            '.'.join(str(v) for v in MINIMUM_VERSION),
            platform.python_version()))

from bibliopixel.main import main

if __name__ == '__main__':
    __spec__ = None
    main.main()
